INSERT INTO  RJ.TICKERS (TICKER_ID, open, CLOSED) VALUES ("IBM", 10.0, 11.0);
INSERT INTO  RJ.TICKERS (TICKER_ID, open, CLOSED) VALUES ("AAPL", 200.0, 203.0);
INSERT INTO  RJ.TICKERS (TICKER_ID, open, CLOSED) VALUES ("CSCO", 22.0, 23.0);
INSERT INTO  RJ.TICKERS (TICKER_ID, open, CLOSED) VALUES ("AMD", 30.0, 27.0);